# Generated by Django 4.2.3 on 2025-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_externalidentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalidentity',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
