# Generated by Django 4.2.3 on 2025-07-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_channel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
