# Generated by Django 4.2.3 on 2025-07-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_channel_remove_post_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
